### Tuple

- tuple is a collection which is ordered and unchangeable/immutable
- written with round brackets
- allow duplicate values
- tuples are indexed, the first item has index [0], the second item has index [1] etc.

#### create tuple

In [6]:
thistuple = ("apple", "banana", "cherry")
print(thistuple)

thistuple = ()
print(thistuple, type(thistuple))

('apple', 'banana', 'cherry')
() <class 'tuple'>

#### create tuple with one item

In [1]:
thistuple = ("apple",) # , at the end is important
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))

<class 'tuple'>
<class 'str'>

#### tuple() Constructor

In [7]:
thistuple = tuple()
print(thistuple,type(thistuple))

thistuple = tuple(["apple", "banana", "cherry"])
print(thistuple,type(thistuple))

() <class 'tuple'>
('apple', 'banana', 'cherry') <class 'tuple'>

#### tuple length

In [ ]:
thistuple = tuple(("apple", "banana", "cherry"))
print(len(thistuple))

3

#### tuple is heterogenous

In [ ]:
tuple1 = ("apple", "banana", "cherry") # str
tuple2 = (1, 5, 7, 9, 3) # int
tuple3 = (True, False, False) # boolean
tuple4 = ("abc", 34, True, 40, "male") # heterogenous
tuple5 = ('a',bool(1)) # any non-zero value: True

print(tuple1)
print(tuple2)
print(tuple3)
print(tuple4)
print(tuple5)

('apple', 'banana', 'cherry')
(1, 5, 7, 9, 3)
(True, False, False)
('abc', 34, True, 40, 'male')
('a', True)

#### type()

In [ ]:
mytuple = ("apple", "banana", "cherry")
print(type(mytuple))

<class 'tuple'>

#### tuple vs lists

- immutable | mutable
- Less memory | More memory [obj.\__sizeof__()]
- **Static** [single block of memory] | Dynamic [two blocks]
- Good for accessing elements | Good for insertion and deletion operations
- implementation  of iterations is faster | time consuming
- limited inbuilt methods | Several inbuilt methods
- **historical, db data** | temp data
- to store a row data | temp row data
- use when we are confident on data | use to contain similar type elements
- to read elements | to update elements

In [15]:
t1 = (1,2,3) # when we need to read elements
l1 = [1,2,3]
l2 = [1,2,3,4]
l3 = [1,2,3,4,5,6,7,8,9,10]
t3 = (1,2,3,4,5,6,7,8,9,10)
t1.__sizeof__(), l1.__sizeof__(), l2.__sizeof__(), l3.__sizeof__(), t3.__sizeof__()

(48, 72, 72, 120, 104)

#### indexing

In [17]:
thistuple = ("apple", "banana", "cherry")
print(thistuple[1])

# print(thistuple[100]) # IndexError: tuple index out of range

banana

***Negative Indexing***

In [ ]:
thistuple = ("apple", "banana", "cherry")
print(thistuple[-1])

cherry

#### slicing

In [ ]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:5])

('cherry', 'orange', 'kiwi')

In [ ]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[:4])

('apple', 'banana', 'cherry', 'orange')

In [ ]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[2:])

('cherry', 'orange', 'kiwi', 'melon', 'mango')

***Negative slicing***

In [ ]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-4:-1]) # -1 index is exclusive
print(thistuple[-4:-1:2]) # start = -4, end = -1, step = 2

('orange', 'kiwi', 'melon')
('orange', 'melon')

#### check tuple item

***in***

In [ ]:
thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

Yes, 'apple' is in the fruits tuple

***not in***

In [ ]:
thistuple = ("apple", "banana", "cherry")
if "mango" not in thistuple: # True
  print("Yes, 'mango' is not in the fruits tuple")

Yes, 'mango' is not in the fruits tuple

#### loop tuple items

In [ ]:
thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)

apple
banana
cherry

In [ ]:
thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple): # len(thistuple) = 3
  print(thistuple[i])
  i = i + 1
# .... out of loop line

# i=0
# 0<3 : True : print t[0] => 'apple' ; i=1
# 1<3 : True : print t[1] => 'banana' ; i=2
# 2<3 : True : print t[2] => 'cherry' ; i=3
# 3<3 : False => out of loop


i = 0
while i < 2:
  print(thistuple[i])
  i = i + 1
# .... out of loop line


# i=0
# 0<2 : True : print t[0] => 'apple' ; i=1
# 1<2 : True : print t[1] => 'banana' ; i=2
# 2<2 : False =>  out of loop

i = 0
while i < len(thistuple): # loop through entire tuple
  print(thistuple[i])
  i = i + 2 # loop through alternate elements
# .... out of loop line

apple
banana
cherry
apple
banana
apple
cherry

#### loop through index numbers

In [ ]:
thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)): # range(0,3) => [0,1,2]
  print(thistuple[i])

apple
banana
cherry

#### Join tuples

In [ ]:
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple1 + tuple2 # joined, but not stored anywhere
print(tuple1, tuple2)

tuple3 = tuple1 + tuple2
print(tuple3)

('a', 'b', 'c') (1, 2, 3)
('a', 'b', 'c', 1, 2, 3)

#### multiply tuples

In [ ]:
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 3
print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')

#### unpack tuple

In [3]:
a=3
a+5

8

In [4]:
_ # last printed value will be stored in _

8

In [8]:
# unpacking

a,b = 1,2

x,*y,z = ('x','y','Y','y','Y','z')
print(x,y,z)

fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits
print(green,tropic,red)
(green, tropic, *red) = fruits
print(green,tropic,red)


fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
(green, _, *red) = fruits # _ is not recommended to use as variable
print(green,_,red)
(green, *_, red) = fruits
print(green,_,red)
a = 3
a+5

x ['y', 'Y', 'y', 'Y'] z
apple ['mango', 'papaya', 'pineapple'] cherry
apple mango ['papaya', 'pineapple', 'cherry']
apple banana ['cherry', 'strawberry', 'raspberry']
apple ['banana', 'cherry', 'strawberry'] raspberry

8

In [9]:
print(_) # _ lost its special property as it is used as variable name

['banana', 'cherry', 'strawberry']

In [ ]:
# fruits = ("apple", "banana", "cherry")
# (green, _) = fruits #ValueError: too many values to unpack (expected 2)
# print(green,_)

In [13]:
employee_details = (101,'Ashok',120000,'Bangalore','Karnataka','India','Datascience department')
_,name,*_,department = employee_details
print(name, department)

Ashok Datascience department

#### update tuple value

In [ ]:
x = ("apple", "banana", "cherry")
y = list(x)

y[1] = "kiwi"

x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')

#### add tuple items

In [ ]:
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)

y.append("orange") # add to the end
thistuple = tuple(y)

print(thistuple)

('apple', 'banana', 'cherry', 'orange')

In [15]:
thistuple = ("apple", "banana", "cherry")
y = ("orange",) # tuple but not str

thistuple = thistuple + y
print(thistuple)

thistuple += y # thistuple = thistuple + y
print(thistuple)

thistuple = y # lost data: apple banana cherry
print(thistuple)

('apple', 'banana', 'cherry', 'orange')
('apple', 'banana', 'cherry', 'orange', 'orange')
('orange',)

In [ ]:
# l1 = [1,2,3] # list
# thistuple += l1
# print(thistuple)

# ----> 9 thistuple += l1
#      10 print(thistuple)
# TypeError: can only concatenate tuple (not "list") to tuple

#### remove tuple item

In [ ]:
thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple") # remove() is list method

thistuple = tuple(y)
print(thistuple)

('banana', 'cherry')

#### delete tuple

In [ ]:
# thistuple = ("apple", "banana", "cherry")
# del thistuple
# print(thistuple) #this will raise an error because the tuple no longer exists

# NameError: name 'thistuple' is not defined

In [ ]:
#del unknownvariable # NameError: name 'unknownvariable' is not defined

#### tuple methods

#### count() method

In [17]:
thistuple = ('1', '3', '7', '8', '7', '5', '4', '6', '8', '5')
x = thistuple.count('5')
print(x)

2

#### index() method

In [18]:
thistuple = ('1', '3', '7', '8', '7', '5', '4', '6', '8', '5')
x = thistuple.index('8') # gives index value of the tuple item
print(x)

3

#### named tuple

- Like dictionaries, they contain keys that are hashed to a particular value.
- But on contrary, it supports both access from key-value and iteration, the functionality that dictionaries lack.
- elements are ordered

In [ ]:
from collections import namedtuple

# Declaring namedtuple()
Student = namedtuple('Student', ['name', 'age', 'DOB']) # Student is tuple name. 'name', 'age', 'DOB' are keys of that tuple

# Adding values
S = Student('Nandini', '19', '25-4-1997')

# Access using index
print('Student age:',S[1])

# Access using name
print('Student name:',S.name)

# Access using getattr()
print('Student DOB:',getattr(S, 'DOB'))

Student age: 19
Student name: Nandini
Student DOB: 25-4-1997

#### conversion operations of named tuple

In [ ]:
S, type(S)

(Student(name='Nandini', age='19', DOB='25-4-1997'), __main__.Student)

In [ ]:
# using _asdict() to return an OrderedDict()
print(S._asdict())

# initializing iterable
li = ['Manjeet', '19', '411997']

# using _make() to return namedtuple()
print(Student._make(li))

# initializing dict
di = {'name': "Nikhil", 'age': 19, 'DOB': '1391997'}

# using ** operator to return namedtuple from dictionary
print(Student(**di))

# using _fields to display all the keynames of namedtuple()
print(S._fields)

# ._replace returns a new namedtuple, it does not modify the original
print(S._replace(name='Manjeet'))
print(S)

{'name': 'Nandini', 'age': '19', 'DOB': '25-4-1997'}
Student(name='Manjeet', age='19', DOB='411997')
Student(name='Nikhil', age=19, DOB='1391997')
('name', 'age', 'DOB')
Student(name='Manjeet', age='19', DOB='25-4-1997')
Student(name='Nandini', age='19', DOB='25-4-1997')

In [22]:
from collections import namedtuple

Point = namedtuple('Point', ['x', 'y'])
p1 = Point(x=1, y=2)
print(type(p1))
print(p1.x, p1.y) # Output: 1 2

p2 = Point(x=3, y=4)
print(type(p1))
print(p2.x, p2.y) # Output: 1 2

<class '__main__.Point'>
1 2
<class '__main__.Point'>
3 4

**above named tuple code has constant time and space complexity**